package com.mayphyr.iotfeign;

import com.mayphyr.iotfeign.rpc.UserClient;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
@EnableFeignClients
public class IotFeignApplication {

    @Autowired
    private static UserClient userClient;

    public static void main(String[] args) {
        SpringApplication.run(IotFeignApplication.class, args);
//        String s = userClient.now2(1);
//        System.out.println(s);
    }

}
