package com.mayphyr.iotbi;

import com.mayphyr.iotbi.manger.AIManger;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import javax.annotation.Resource;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
public class IotBiApplication {

    public static void main(String[] args) {
        SpringApplication.run(IotBiApplication.class, args);


    }

}
