package com.mayphyr.iotdecider;

import com.mayphyr.iotfeign.config.DefaultFeignConfig;

import com.mayphyr.iotfeign.rpc.UserClient;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
@EnableFeignClients(clients = {UserClient.class},defaultConfiguration = DefaultFeignConfig.class)
public class IotDeciderApplication {

    public static void main(String[] args) {
        SpringApplication.run(IotDeciderApplication.class, args);
    }

}
