package com.mayphyr.iotreception;

import com.mayphyr.iotfeign.config.DefaultFeignConfig;
import com.mayphyr.iotfeign.rpc.agrculture.NodeClient;
import com.mayphyr.iotreception.mqtt.client.EmqClient;
import com.mayphyr.iotreception.mqtt.publish.properties.MqttProperties;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;

import javax.annotation.PostConstruct;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
@EnableFeignClients(clients = {NodeClient.class},defaultConfiguration = DefaultFeignConfig.class)
public class IotReceptionApplication {

    public static void main(String[] args) {
        SpringApplication.run(IotReceptionApplication.class, args);
    }

    @Autowired
    private EmqClient emqClient;
    @Autowired
    private MqttProperties mqttProperties;

    @PostConstruct
    public void  init() throws InterruptedException {
        //配置连接信息
        emqClient.connect(mqttProperties.getUsername(), mqttProperties.getPassword());
//        emqClient.subscribe(mqttProperties.getHardTopic(), QosEnum.QOS0);
//        while (true){
//            emqClient.publish(mqttProperties.getWebTopic(),"sjidsdjs", QosEnum.QOS0, false);
//            TimeUnit.SECONDS.sleep(1);
//
//        }
    }

}
